@token = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJQcmFjdGl0aW9uZXIvZGV2LWFyenQxIiwidXNlcm5hbWUiOiJhcnp0MSIsInJvbGUiOiJBUlpUIiwiaWF0IjoxNzY1OTE0NjUxLCJleHAiOjE3NjU5NTc4NTF9.h9lJ9in-OeaLuktELOQB2cfZrYf00ROTp2p353nmW9Q0vaOdvJMjufWPzawu0jDe

### Arzt Login (DevSeed)
POST http://localhost:8080/api/auth/arzt/login
Content-Type: application/json

{
  "username": "arzt1",
  "password": "arztpass"
}

###
# 1) Arzt Login, token
# 2) Zur Authorization hinzufügen
### (NEU) Draft-Patient + Code generieren (ARZT, JWT nötig)
POST http://localhost:8080/api/auth/patients/generate-code
Authorization: Bearer {{token}}

###


### Patient First Login (public)
POST http://localhost:8080/api/auth/patient/first-login
Content-Type: application/json

{
  "code": "DCJEUM",
  "consentAccepted": true,
  "givenName": "Valentina",
  "familyName": "Aseeva",
  "birthYear": 1996,
  "password": "meinpasswort"
}

### Patient Login (последующие входы)
POST http://localhost:8080/api/auth/patient/login
Content-Type: application/json

{
  "username": "L82FBRYS",
  "password": "meinpasswort"
}
